### ISSUE TITLE
Build skeleton code

### ISSUE THREAD

**Issue by nicholaswmin** [TheProfs/object-sync#1]
Build initial skeleton code to get up and running.

## Todos

- [x] Add tests
- [x] Get some initial code up and running
- [x] Add some documentation 
- [x] Integrate with Travis CI
