### ISSUE TITLE
Prepare for production release

### ISSUE THREAD

**Issue by nicholaswmin** [TheProfs/object-sync#4]
## Todos

- [ ] Reuse `iron-ajax`'s debounce prop, instead of debouncing this element's functions
- [ ] Fix bug where `changes.value` is sent instead of `changes.base` on remote saves
- [ ] Resolve dependencies
- [ ] Publish on Bower
