### ISSUE TITLE
Fix remote request formats

### ISSUE THREAD

**Issue by nicholaswmin** [TheProfs/object-sync#5]
## Todos

- [x] Add `application/json` content type for `PUT` requests
- [x] Send whole object when saving via `PUT` instead of just value
- [x] Allow specifying authentication headers
